version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: securestorage_app:latest
    container_name: securestorage_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env:ro
      - storage_uploads:/var/www/storage/app/public
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:p8gz8aBS4wWcqiUL/48UEJs0RFN3e7viAnyQMwjBQeA=
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=secure_storage
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: securestorage_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - storage_uploads:/var/www/storage/app/public
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: securestorage_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: secure_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
  storage_uploads:
